import pathlib,json,datetime
from preflight import R,D,sha,read,write,verify
assert not (D/'opened.json').exists()
verify()
m=read(R/'evidence/heldout_gate_manifest.json')
files={str(p.relative_to(R)):sha(p) for p in sorted((R/'candidate/epoch003').glob('*.py'))}
for rel in ['evidence/heldout_gate_manifest.json','control/EPOCH_003_HUMAN_AUTHORIZATION.json','control/EPOCH_003_AUTHORITY.yaml','evidence/epoch002/environment.json','evidence/epoch002/protocol.json','evidence/epoch002/affine_typed_seed.json','evidence/epoch002/reduction_typed_seed.json']:files[rel]=sha(R/rel)
preserved={str(p.relative_to(R)):sha(p) for folder in ['candidate/epoch002','evidence/epoch002','champion'] for p in (R/folder).rglob('*') if p.is_file() and '__pycache__' not in p.parts}
for rel in ['checkpoints/C_035.json','checkpoints/C_124.json','checkpoints/C_125.json','evidence/EPOCH002_REPORT.md','evidence/heldout_gate_manifest.json']:preserved[rel]=sha(R/rel)
copies={p.name:{'source':'candidate/epoch002/'+p.name,'sha256':sha(p)} for p in (R/'candidate/epoch003').glob('*.py') if (R/'candidate/epoch002'/p.name).exists() and sha(p)==sha(R/'candidate/epoch002'/p.name)}
f={'frozen_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'heldout_opened':False,'files':files,'preserved':preserved,'copied_components':copies,'methods':['B0','B3','FULL_A'],'secondary':{'B1':'NOT_RUN_BUDGET_CONSTRAINT','B2':'NOT_RUN_BUDGET_CONSTRAINT'},'cases':{s:m['splits'][s]['specification'] for s in ['G2','G3']},'execution_order':[[s,method] for s in ['G2','G3'] for method in ['B0','B3','FULL_A']],'implementation':'v1','implementation_rationale':'one original candidate policy per split, no development change scenarios; v2 and slow remain frozen source components but are not additional cases','weights':'equal positive unit weight for every listed shape, matching original development seed objective','initial_evidence_state':'independent copy of frozen Epoch002 path seed for each method; none of the heldout shapes match cache scopes or shape-indexed ranking priors; effective cache and prior empty','policy':'byte-identical Epoch002 planner; B0 ascending all shapes; B3 largest weighted shape first and safe reject; FULL_A impact/cost defaults and largest-shape tie break, safe reject','sampler':{'paired_samples':61,'warmup_calls':30,'batch_calls':100},'oracle':'byte-identical frozen worker and operations CPU float64 oracle','aggregation':m['metrics_and_thresholds'],'budget':{'inherited_live_cells':158,'max_additional':22,'primary_max':21,'spare':'only exact-hash quarantined operational rerun; no automatic rerun','sampled_seconds_cumulative_max':600,'heldout_wall_seconds_max':10800,'max_cells_per_method_case':5},'no_promotion':True,'acceptance_code':'candidate/epoch003/audit.py','limitations':['Only v1 candidate per split, no claim over v2/slow enumerated manifest versions.','Uniform weights fixed before opening because heldout manifest does not specify weights.','Exact seven new shapes have no scope-compatible historical measurements; historical evidence is not extrapolated.']}
write(D/'preopen_freeze.json',f);(D/'preopen_freeze.sha256').write_text(sha(D/'preopen_freeze.json')+'  preopen_freeze.json\n');print(sha(D/'preopen_freeze.json'))
